/*
First time? Check out the tutorial game:
https://sprig.hackclub.com/gallery/getting_started

@title: Tetris
@author: BonzaiDev, Adrian T
@tags: []
@addedOn: 2024-07-23
*/

// Game settings
const blockSpawnPosition = {x: 5, y: 2};

const gameMap = map`
............
............
............
............
............
............
............
............
............
............
............
............`

// Sprites
const player = "p";

setLegend(
  [ player, bitmap`
................
................
................
.......0........
.....00.000.....
....0.....00....
....0.0.0..0....
....0......0....
....0......0....
....00....0.....
......00000.....
......0...0.....
....000...000...
................
................
................`]
);

// Inputs
onInput("w", () => {
  console.log("rotating");
});

onInput("s", () => {
  console.log("down");
});

onInput("a", () => {
  console.log("left");
});

onInput("d", () => {
  console.log("right");
});

// Game logic
setMap(gameMap)

addSprite(blockSpawnPosition.x, blockSpawnPosition.y, player);

